# Generated by Django 3.0.8 on 2020-08-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Genre', models.CharField(max_length=10)),
                ('Artist', models.TextField(max_length=500)),
                ('Song', models.TextField(max_length=500)),
                ('DatePublihsed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Type', models.CharField(choices=[('band', 'Band'), ('Solo', 'Solo')], default='band', max_length=10)),
                ('Album', models.TextField(max_length=500)),
                ('Song', models.TextField(max_length=500)),
                ('PreferredGenre', models.CharField(max_length=15)),
                ('DateOfFormationorBirth', models.DateField()),
                ('Bio', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Genre', models.CharField(max_length=10)),
                ('Artist', models.CharField(max_length=15)),
                ('Album', models.CharField(max_length=15)),
            ],
        ),
    ]
