# Generated by Django 3.0.8 on 2020-08-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='Album',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
