# Generated by Django 3.0.8 on 2020-08-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
