# Generated by Django 3.0.8 on 2020-08-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_song_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='Type',
            new_name='Form',
        ),
    ]
